name: .NET Publish on Commit

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: windows-latest  # Ensure Windows environment for win-x86

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Publish
        run: |
          dotnet publish -r win-x86 -c Release -p:PublishSingleFile=true --self-contained true 

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: bin\Release\net8.0\win-x86\publish\  # Adjust if your publish folder differs
